AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  user

  SAM Template for user
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  UserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      VpcConfig:
        SecurityGroupIds: [sg-42f22837]
        SubnetIds: [subnet-2e6c1a06,subnet-0c773347,subnet-3e5b6e64,subnet-37fda64e]
      Events:
        getUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user/{id}
            Method: get
        getUsers:
          Type: Api
          Properties:
            Path: /user
            Method: get
        createUser:
          Type: Api 
          Properties:
            Path: /user
            Method: post
        deleteUser:
          Type: Api 
          Properties:
            Path: /user/{id}
            Method: delete
        patchUser:
          Type: Api 
          Properties:
            Path: /user/{id}
            Method: patch
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UserApi:
    Description: "API Gateway endpoint URL for Prod stage for User function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/user/"
  UserFunction:
    Description: "User Lambda Function ARN"
    Value: !GetAtt UserFunction.Arn
  # UserIamRole:
  #   Description: "Implicit IAM Role created for User Function"
  #   Value: !GetAtt UserIAMRole.Arn
